# Generated by Django 3.2.20 on 2023-07-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230720_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text2',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='text3',
            field=models.CharField(default='', max_length=250),
        ),
    ]
